# Generated by Django 4.2.2 on 2024-03-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_alter_attendance_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
