# Generated by Django 4.2.2 on 2024-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_leave_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='iot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField()),
            ],
        ),
    ]
