# Generated by Django 4.2.11 on 2024-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_iot'),
    ]

    operations = [
        migrations.CreateModel(
            name='circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
