# Generated by Django 4.2.11 on 2024-04-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_circulars_delete_circular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulars',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
