# Generated by Django 4.2.11 on 2024-04-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_circular_delete_circulars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
