# Generated by Django 4.2.11 on 2024-04-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_alter_circular_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
