# Generated by Django 4.2.11 on 2024-05-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_batch_alter_staff_mobile_alter_student_record_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='sem',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')]),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='workingday',
            field=models.IntegerField(),
        ),
    ]
