# Generated by Django 4.2.11 on 2024-05-11 13:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0019_profiles_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profiles',
            new_name='Profile',
        ),
    ]
