# Generated by Django 5.0.6 on 2024-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0022_alter_department_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_letter',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
