# Generated by Django 5.0.6 on 2024-07-15 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_leave_letter_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.batch'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
