# Generated by Django 5.0.6 on 2024-07-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0024_attendance_batch_attendance_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingday',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], default=1, max_length=3),
        ),
    ]
